baseURL = "https://flightops.news/"
languageCode = "en-us"
title = "FlightOps.News"

[params]
  description = "The trusted voice on what's currently emerging in Digital Flight Operations Technology"

[markup.goldmark.renderer]
  unsafe = true

[permalinks]
  posts = "/posts/:slug/"
